### ISSUE TITLE
Register package after fixing issues

### ISSUE THREAD

**Issue by aivuk** [pinheiroGroup/Kinbiont.jl#61]
@JuliaRegistrator register()

**Comment by DilumAluthge** [comment]
[I don't have commit access on this repo. Therefore, the following comment should cause the bot to respond with a comment saying that I don't have access.]

**Comment by DilumAluthge** [comment]
@JuliaRegistrator register

**Comment by DilumAluthge** [comment]
Okay, so the bot is correctly installed on this repo, and it is able to respond to comments.

@aivuk Can you post another `@JuliaRegistrator register` comment on this issue? Let's see if it works a second time.

**Comment by aivuk** [comment]
@JuliaRegistrator register()

**Comment by aivuk** [comment]
thanks all, maybe it was some spam protection system because I triggered multiple times in a short time? Well, just tried again, let's see how it goes.

**Comment by aivuk** [comment]
@JuliaRegistrator register

**Comment by DilumAluthge** [comment]
@JuliaRegistrator register

**Comment by DilumAluthge** [comment]
This seems like a bug in JuliaRegistrator. I'll ping someone in the Julia Slack (in the `#pkg-registration` channel) to look at the server logs.

**Comment by aivuk** [comment]
@JuliaRegistrator register
